services:
  gosocial:
    build:
      context: ./cmd
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      REST_PORT: ":8080"
      DB_CONNECTION: "host=postgres port=5432 user=postgres password=postgres dbname=social_db sslmode=disable"
      DB_DRIVER: "postgres"
      PRIVATE_KEY_PATH: "private_key.pem"
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: 'postgres:16.3-alpine'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "social_db"
    volumes:
      - ./db_data/postgres/:/var/lib/postgresql/data
      - ./dbscripts/public_schema.sql:/docker-entrypoint-initdb.d/public_schema.sql