services:
  gosocial:
    build:
      context: ./cmd
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      REST_PORT: ":8080"
      DB_CONNECTION: "host=postgres port=5432 user=admin password=secret dbname=social_db sslmode=disable"
      DB_USERNAME: "admin"
      DB_PASSWORD: "secret"
      DB_DATABASE: "social_db"
      DB_DRIVER: "postgres"
      PRIVATE_KEY_PATH: "./app/private_key.pem"
      MAIL_DOMAIN: localhost
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_ENCRYPTION: none
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      MAIL_FROMNAME: "Max Mustermann"
      MAIL_FROMADDRESS: "max.mustermann@test.com"
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: 'postgres:16.3-alpine'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "social_db"
    volumes:
      - ./db_data/postgres/:/var/lib/postgresql/data
      - ./dbscripts/public_schema.sql:/docker-entrypoint-initdb.d/public_schema.sql
  
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - "1025:1025"
      - "8025:8025"