name: CD

on:
  push:
    branches: [main]

jobs:
  build_push_image:
    name: Build Docker Image and push to Container Registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Generate private key
        run: make key
      
      - name: Set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >> ${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
      
      - name: Build and push image
        run: |
          cd cmd
          docker build . --tag ghcr.io/${{ env.OWNER_LC }}/go-social:latest
          docker push ghcr.io/${{ env.OWNER_LC }}/go-social:latest
